
IF OBJECT_ID('COO_CustomsData', 'U') IS NOT NULL DROP TABLE COO_CustomsData;
CREATE TABLE COO_CustomsData (
    [Id] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [ImportDate] DATETIME,
    [STT] NVARCHAR(500),
    [Số TK] NVARCHAR(500),
    [Ngày ĐK] NVARCHAR(500),
    [Mã loại hình] NVARCHAR(500),
    [Mã địa điểm đích] NVARCHAR(500),
    [Tên địa điểm đích cho vận chuyển bảo thuế] NVARCHAR(500),
    [Địa điểm dỡ hàng] NVARCHAR(500),
    [Mã hiệu PTVC] NVARCHAR(500),
    [Ngày khởi hành vận chuyển] NVARCHAR(500),
    [Ký hiệu và số hiệu bao bì] NVARCHAR(500),
    [Tỷ giá thanh toán] NVARCHAR(500),
    [Đơn vị tiền tệ] NVARCHAR(500),
    [Số lượng kiện] NVARCHAR(500),
    [Mã ĐVT kiện] NVARCHAR(500),
    [Trọng lượng] NVARCHAR(500),
    [Mã ĐVT trọng lượng] NVARCHAR(500),
    [Số quản lý nội bộ] NVARCHAR(500),
    [Điều kiện giá hóa đơn] NVARCHAR(500),
    [Ghi chú] NVARCHAR(500),
    [STT hàng] NVARCHAR(500),
    [Mã NPL/SP] NVARCHAR(500),
    [Mã HS] NVARCHAR(500),
    [Tên hàng] NVARCHAR(500),
    [Xuất xứ] NVARCHAR(500),
    [Đơn giá] NVARCHAR(500),
    [Đơn giá tính thuế] NVARCHAR(500),
    [Tổng số lượng] NVARCHAR(500),
    [Đơn vị tính] NVARCHAR(500),
    [Tổng số lượng_1] NVARCHAR(500),
    [Đơn vị tính_1] NVARCHAR(500),
    [Trị giá NT] NVARCHAR(500),
    [Tổng trị giá] NVARCHAR(500),
    [Mã biểu thuế] NVARCHAR(500),
    [Thuế suất XNK] NVARCHAR(500),
    [Tiền thuế XNK] NVARCHAR(500),
    [Số tiền miễn thuế XNK] NVARCHAR(500),
    [Thuế suất TV] NVARCHAR(500),
    [Tiền thuế TV] NVARCHAR(500),
    [Thuế suất PB] NVARCHAR(500),
    [Tiền thuế PB] NVARCHAR(500),
    [Thuế suất TTĐB] NVARCHAR(500),
    [Tiền thuế TTĐB] NVARCHAR(500),
    [Thuế suất BVMT] NVARCHAR(500),
    [Tiền thuế MT] NVARCHAR(500),
    [Thuế suất VA] NVARCHAR(500),
    [Tiền thuế VAT] NVARCHAR(500),
    [Tổng tiền thuế] NVARCHAR(500),
    [Mã doanh nghiệp] NVARCHAR(500),
    [Tên doanh nghiệp] NVARCHAR(500),
    [Tên đối tác] NVARCHAR(500),
    [Số hóa đơn] NVARCHAR(500),
    [Ngày hóa đơn] NVARCHAR(500),
    [Số hợp đồng] NVARCHAR(500),
    [Ngày hợp đồng] NVARCHAR(500)
);

IF OBJECT_ID('COO_ConsumptionData', 'U') IS NOT NULL DROP TABLE COO_ConsumptionData;
CREATE TABLE COO_ConsumptionData (
    [Id] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [ImportDate] DATETIME,
    [Col0] NVARCHAR(500),
    [Col1] NVARCHAR(500),
    [Col2] NVARCHAR(500),
    [Col3] NVARCHAR(500),
    [Col4] NVARCHAR(500),
    [Col5] NVARCHAR(500),
    [Có xuất xứ] NVARCHAR(500),
    [Không có xuất xứ] NVARCHAR(500),
    [Col8] NVARCHAR(500),
    [Số] NVARCHAR(500),
    [Ngày] NVARCHAR(500),
    [Số_1] NVARCHAR(500),
    [Ngày_1] NVARCHAR(500),
    [Customer order No.] NVARCHAR(500),
    [Unit Of FG] NVARCHAR(500),
    [Customs code] NVARCHAR(500),
    [Viet Nam name FG] NVARCHAR(500),
    [Material Code] NVARCHAR(500),
    [Eng name FG] NVARCHAR(500),
    [PO+Customs Code] NVARCHAR(500)
);
