@echo off
ren bump.js bump.cjs
node bump.cjs
echo Building Vite...
call npx vite build > nul 2>&1
echo Copying to server...
xcopy dist\* "\\192.168.14.10\C\Program Files\Ampps\www\trax-eco\" /S /E /Y /C /H > nul 2>&1
echo Copying APK for OTA...
copy /Y "android\app\build\outputs\apk\debug\app-debug.apk" "\\192.168.14.10\C\Program Files\Ampps\www\trax-eco\TraxEco_v1.1.1.apk" > nul 2>&1
echo Syncing capacitor...
call npx cap sync android
cd android
echo Building APK...
call .\gradlew assembleDebug
echo Done!
