const fs = require('fs');

const enMap = {
  "scanout_subtitle": "Scan QR Code to take out item → enter Holder + Qty → update inventory",
  "scanout_success": "Scan Out successful! Inventory has been updated.",
  "scanout_step1": "Step 1 — Scan QR Code",
  "scanout_step1_desc": "Use camera device or barcode scanner",
  "scanout_point_qr": "Point QR into frame",
  "scanout_open_cam": "Open Camera (coming soon)",
  "scanout_or": "or",
  "scanout_manual_input": "Enter QR / Item Code manually...",
  "scanout_not_found": "No item found with this code.",
  "scanout_step2": "Step 2 — Item recognized",
  "scanout_qr_valid": "QR Valid",
  "scanout_type": "Type",
  "scanout_no_item": "No item - please scan or enter code in Step 1.",
  "scanout_step3": "Step 3 — Confirm Scan Out",
  "scanout_holder_req": "Holder (Borrower) *",
  "scanout_select_staff": "Select staff...",
  "scanout_qty_out": "Quantity to take out *",
  "scanout_note_opt": "Note (optional)",
  "scanout_confirm_btn": "Confirm Scan Out",
  "scanout_log": "Recent Scan Out Log",
  "print_back": "Back",
  "print_loading": "Loading...",
  "print_title": "Print Label / QR Code",
  "print_item_info": "Item Information",
  "print_name": "Name",
  "print_settings": "Print Settings",
  "print_size": "Label Size",
  "print_copies": "Print Copies"
};

const viMap = {
  "scanout_subtitle": "Scan QR Code để lấy item ra khỏi vị trí → nhập Holder + Qty → cập nhật inventory",
  "scanout_success": "Scan Out thành công! Tồn kho đã được cập nhật.",
  "scanout_step1": "Bước 1 — Scan QR Code",
  "scanout_step1_desc": "Dùng camera device hoặc máy scan barcode",
  "scanout_point_qr": "Hướng QR vào khung",
  "scanout_open_cam": "Mở Camera (coming soon)",
  "scanout_or": "hoặc",
  "scanout_manual_input": "Nhập QR / Item Code thủ công…",
  "scanout_not_found": "Không tìm thấy item với mã này.",
  "scanout_step2": "Bước 2 — Item được nhận diện",
  "scanout_qr_valid": "QR hợp lệ",
  "scanout_type": "Loại",
  "scanout_no_item": "Chưa có item — hãy scan hoặc nhập mã ở Bước 1.",
  "scanout_step3": "Bước 3 — Xác nhận Scan Out",
  "scanout_holder_req": "Holder (Người mượn) *",
  "scanout_select_staff": "Chọn nhân viên…",
  "scanout_qty_out": "Số lượng lấy ra *",
  "scanout_note_opt": "Ghi chú (tùy chọn)",
  "scanout_confirm_btn": "Xác nhận Scan Out",
  "scanout_log": "Lịch sử Scan Out gần đây",
  "print_back": "Quay lại",
  "print_loading": "Đang tải...",
  "print_title": "In Label / QR Code",
  "print_item_info": "Thông tin Item",
  "print_name": "Tên",
  "print_settings": "Cài đặt in",
  "print_size": "Kích thước Label",
  "print_copies": "Số lượng in",
  "edit_fabric_hanger": "Chỉnh sửa Vải Hanger",
  "add_fabric_hanger": "Thêm Vải Hanger",
  "material_images": "Hình ảnh Vật tư",
  "library": "Thư viện",
  "camera": "Máy ảnh",
  "description": "Mô tả (Description)",
  "technical_specs_title": "Thông số kỹ thuật",
  "cost_quantity": "Chi phí & Số lượng",
  "cancel": "Hủy",
  "save": "Lưu lại"
};

// Instead of regex replaces that could be risky, I will just manually edit the files.
// Let's create an ordered list of what to insert for {}.
console.log('Use multi_replace_file_content to insert keys directly in the files instead of writing a parser script.');
